# 레시피북 일기 스티커의 원본. 글자 하나가 도트 하나인 16x16 격자.
# 고친 뒤 이 폴더에서 `python3 draw.py` 를 돌리면 sticker_1.png ~ 이 다시 만들어집니다. (Pillow 필요)
# 장수가 바뀌면 config.js의 sticker_count와 service-worker.js의 목록도 같이 고쳐 주세요.
import os
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
PAL = {
 '.': None, 'K': (58,42,38), 'W': (255,250,245), 'w': (226,216,210), 'm': (170,158,156),
 'Y': (255,213,79), 'y': (245,166,35), 'C': (255,236,179), 'O': (255,167,64), 'o': (230,126,34),
 'R': (239,83,80), 'r': (198,40,40), 'P': (255,138,128), 'p': (255,205,210),
 'G': (129,199,132), 'g': (56,142,60), 'B': (161,110,72), 'b': (222,184,135), 'T': (201,140,80),
 'N': (55,60,75), 'S': (128,216,255), 's': (66,165,245), 'I': (214,242,255),
 'V': (179,157,219), 'v': (126,87,194),
}
ART = {}
ART['rice'] = """
................
................
.....KKKKKK.....
...KKWWWWWWKK...
..KWWWWWWWWWWK..
.KWWWwWWWWwWWWK.
.KWWWWWWwWWWWWK.
KKKKKKKKKKKKKKKK
KSSSSSSSSSSSSSSK
KSsSSSSSSSSSSsSK
.KSSSSSSSSSSSSK.
.KSsSSSSSSSSsSK.
..KSSSSSSSSSSK..
...KKSSSSSSKK...
....KKKKKKKK....
................"""
ART['egg'] = """
................
................
....KKKKK.......
..KKWWWWWKKK....
.KWWWWWWWWWWK...
.KWWWWWWWWWWWK..
KWWWWKKKKWWWWWK.
KWWWKYYYYKWWWWK.
KWWWKYCYYKWWWWK.
KWWWKYYYYKWWWWK.
.KWWWKKKKWWWWK..
.KWWWWWWWWWWWK..
..KWWWWWWWWKK...
...KKKWWWKK.....
......KKK.......
................"""
ART['onigiri'] = """
................
.......KK.......
......KWWK......
.....KWWWWK.....
.....KWWWWK.....
....KWWWWWWK....
....KWWWWWWK....
...KWWWWWWWWK...
...KWWWWWWWWK...
..KWWNNNNNNWWK..
..KWWNNNNNNWWK..
.KWWWNNNNNNWWWK.
.KWWWNNNNNNWWWK.
.KWWWNNNNNNWWWK.
..KKKKKKKKKKKK..
................"""
ART['strawberry'] = """
................
.....g..gg......
....gGggGg.g....
...gGGGGGGgG....
..KKgGGGGgKKK...
.KRRRgGGgRRRRK..
.KRRCRRRRRRCRK..
KRRRRRRCRRRRRRK.
KRRCRRRRRRRCRRK.
KRRRRRCRRRRRRRK.
.KRRRRRRRCRRRK..
.KRRCRRRRRRRRK..
..KRRRRCRRRRK...
...KRRRRRRRK....
....KKRRRKK.....
......KKK......."""
ART['mug'] = """
................
....m..m..m.....
...m..m..m......
....m..m..m.....
................
.KKKKKKKKKKK....
.KBBBBBBBBBKKKK.
.KWWWWWWWWWK..K.
.KWWWWWWWWWK..K.
.KWWWWWWWWWK..K.
.KWWWWWWWWWKKK..
.KWWWWWWWWWK....
..KWWWWWWWK.....
...KKKKKKK......
................
................"""
ART['heart'] = """
................
................
...KKK....KKK...
..KPPPK..KPPPK..
.KPpPPPKKPPPPPK.
.KPpPPPPPPPPPPK.
.KPPPPPPPPPPPPK.
.KPPPPPPPPPPPPK.
..KPPPPPPPPPPK..
...KPPPPPPPPK...
....KPPPPPPK....
.....KPPPPK.....
......KPPK......
.......KK.......
................
................"""
ART['star'] = """
................
.......KK.......
......KYYK......
......KYYK......
.....KYYYYK.....
KKKKKKYYYYKKKKKK
KYYYYYYYYYYYYYYK
.KYYYYYYYYYYYYK.
..KYYYYYYYYYYK..
...KYYYYYYYYK...
...KYYYYYYYYK...
..KYYYYKKYYYYK..
..KYYYK..KYYYK..
.KYYKK....KKYYK.
.KKK........KKK.
................"""
ART['cat'] = """
................
.KK..........KK.
.KOK........KOK.
.KOOK......KOOK.
.KOpOKKKKKKOpOK.
.KOOOOOOOOOOOOK.
KOOOOOOOOOOOOOOK
KOOOKOOOOOOKOOOK
KOOOKOOOOOOKOOOK
KOOOOOOPPOOOOOOK
KOOWWOOKKOOWWOOK
KOWWWWKOOKWWWWOK
.KOWWWOOOOWWWOK.
..KKOOOOOOOOKK..
....KKKKKKKK....
................"""
ART['dog'] = """
................
..KKKK....KKKK..
.KBBBBKKKKBBBBK.
KBBBbbbbbbbbBBBK
KBBbbbbbbbbbbBBK
KBBbbbbbbbbbbBBK
KBBbKbbbbbbKbBBK
KBKbKbbbbbbKbKBK
.K.KbbbWWbbbK.K.
...KbbWKKWbbK...
...KbbWWWWbbK...
...KbbWKKWbbK...
....KbbWWbbK....
.....KKKKKK.....
................
................"""
ART['rabbit'] = """
....KK....KK....
...KWWK..KWWK...
...KWpK..KpWK...
...KWpK..KpWK...
...KWpK..KpWK...
...KWWKKKKWWK...
..KWWWWWWWWWWK..
.KWWWWWWWWWWWWK.
.KWWKWWWWWWKWWK.
.KWWKWWWWWWKWWK.
.KWpWWWPPWWWpWK.
.KWWWWWKKWWWWWK.
..KWWWWWWWWWWK..
...KKWWWWWWKK...
.....KKKKKK.....
................"""
ART['bear'] = """
................
..KKK......KKK..
.KBBBK....KBBBK.
.KBbBKKKKKKBbBK.
.KBBBBBBBBBBBBK.
..KBBBBBBBBBBK..
.KBBBBBBBBBBBBK.
.KBBKBBBBBBKBBK.
.KBBKBBBBBBKBBK.
.KBBBBbbbbBBBBK.
.KBBBbbKKbbBBBK.
.KBBBbbbbbbBBBK.
..KBBBbbbbBBBK..
...KKBBBBBBKK...
.....KKKKKK.....
................"""
ART['chick'] = """
................
................
.....KKKKKK.....
....KYYYYYYK....
...KYYYYYYYYK...
..KYYYYYYYYYYK..
..KYYKYYYYKYYK..
..KYYKYYYYKYYK..
.KYYYYYOOYYYYYK.
.KYpYYOOOOYYpYK.
.KYYYYYOOYYYYYK.
..KYYYYYYYYYYK..
..KYYYYYYYYYYK..
...KKYYYYYYKK...
.....KKKKKK.....
................"""
ART['toast'] = """
................
..KKKK....KKKK..
.KTTTTKKKKTTTTK.
KTCCCCTTTTCCCCTK
KTCCCCCCCCCCCCTK
KTCCCCCCCCCCCCTK
.KTCCCCCCCCCCTK.
.KTCCCYYYYCCCTK.
.KTCCCYYYYCCCTK.
.KTCCCCYYCCCCTK.
.KTCCCCCCCCCCTK.
.KTCCCCCCCCCCTK.
.KTCCCCCCCCCCTK.
.KTTTTTTTTTTTTK.
..KKKKKKKKKKKK..
................"""
ART['apple'] = """
................
........KK......
.......KBK.gg...
......KBKgGGg...
...KKKKBKKgg....
..KRRRRKRRRRK...
.KRRpRRRRRRRRK..
KRRpRRRRRRRRRRK.
KRRpRRRRRRRRRRK.
KRRRRRRRRRRRRRK.
KRRRRRRRRRRRRRK.
KRRRRRRRRRRRrRK.
.KRRRRRRRRRrRK..
.KRRRRRRRRRRRK..
..KKRRRKKRRKK...
....KKK..KK....."""
ART['mushroom'] = """
................
.....KKKKKK.....
...KKRRRRRRKK...
..KRRWWRRRRRRK..
.KRRRWWRRRWWRRK.
.KRRRRRRRRWWRRK.
KRRWWRRRRRRRRRRK
KRRWWRRRRRRRRRRK
KKKKKKKKKKKKKKKK
...KCCCCCCCCK...
...KCCCCCCCCK...
...KCCKCCKCCK...
...KCCCCCCCCK...
....KCCCCCCK....
.....KKKKKK.....
................"""
ART['skull'] = """
................
....KKKKKKKK....
...KWWWWWWWWK...
..KWWWWWWWWWWK..
.KWWWWWWWWWWWWK.
.KWWWWWWWWWWWWK.
.KWKKKWWWWKKKWK.
.KWKKKWWWWKKKWK.
.KWWKKWWWWKKWWK.
.KWWWWWKKWWWWWK.
..KwWWWKKWWWwK..
...KKWWWWWWKK...
....KWKWWKWK....
....KWKWWKWK....
....KKKKKKKK....
................"""
ART['fire'] = """
................
.......K........
......KRK.......
......KRRK......
.....KRRRK..K...
....KRROORK.KK..
...KRROOORRKRK..
..KRROOOORRRRK..
..KRROYYOORRRK..
.KRROOYYYOORRRK.
.KRROYYYYOORRRK.
.KRROYYCYYORRRK.
.KRRROYCCYORRK..
..KRRROYYORRRK..
...KKRRRRRRKK...
.....KKKKKK....."""
ART['note'] = """
................
......KKKKKKKKK.
......KVVVVVVVK.
......KVVVVVVVK.
......KVKKKKKVK.
......KVK...KVK.
......KVK...KVK.
......KVK...KVK.
......KVK...KVK.
...KKKKVK.KKKVK.
..KVVVVVKKVVVVK.
.KVVVVVVKVVVVVK.
.KVvVVVVKVvVVVK.
.KVVVVVK.KVVVK..
..KKKKK...KKK...
................"""
ART['ice'] = """
................
................
....KKKKKKKKK...
...KIIIIIIIIIK..
..KIIWWIIIIIISK.
.KKKKKKKKKKKSSK.
.KSSSSSSSSSKSSK.
.KSWWSSSSSSKSSK.
.KSWSSSSSSSKSsK.
.KSSSSSSSSSKSsK.
.KSSSSSSSSSKSsK.
.KSSSSSSSWSKsK..
.KSSSSSSWWSKK...
.KKKKKKKKKKK....
................
................"""
ART['thumbsup'] = """
................
.......KK.......
......KYYK......
......KYYK......
.....KYYYK......
.....KYYK.......
....KYYYKKKKKK..
.KKKKYYYYYYYYYK.
.KssKYYYYYYYYYK.
.KssKYYYYYYYKK..
.KssKYYYYYYYYK..
.KssKYYYYYYYKK..
.KssKYYYYYYYYK..
.KssKYYYYYYYK...
.KKKKKKKKKKKK...
................"""
ORDER = list(ART)
if __name__ == '__main__':
    tiles = []
    for i, name in enumerate(ORDER, 1):
        rows = ART[name].strip('\n').split('\n')
        assert len(rows) == 16 and all(len(r) == 16 for r in rows), (name, [len(r) for r in rows])
        im = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if PAL[ch]: im.putpixel((x, y), PAL[ch] + (255,))
        im.save(os.path.join(HERE, f'sticker_{i}.png')); tiles.append(im)
    print(len(tiles), '장:', ', '.join(f'{i}={n}' for i, n in enumerate(ORDER, 1)))
